function requireLogin(){if(!localStorage.getItem("username"))location.replace("login.html")}
function today(){return new Date().toISOString().slice(0,10)}
function renderNavbar(){const n=document.querySelector(".navbar");if(!n)return;const page=location.pathname.split("/").pop()||"index.html";const user=localStorage.getItem("username")||"Admin";n.innerHTML=`<a href="index.html" class="navbar-brand">Absensi Siswa</a><ul class="navbar-menu"><li><a href="index.html" class="${page==="index.html"?"active":""}">Dashboard</a></li><li><a href="input_absensi.html" class="${page==="input_absensi.html"?"active":""}">Input Absensi</a></li><li><a href="tampil_siswa.html" class="${["tampil_siswa.html","tambah_siswa.html","edit_siswa.html"].includes(page)?"active":""}">Data Siswa</a></li></ul><div class="navbar-user"><span>Halo, <strong>${escapeHtml(user)}</strong></span><a href="logout.html" class="btn-logout" onclick="return confirm('Apakah Anda yakin ingin keluar?')">Logout</a></div>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function updateDashboard(){const s=JSON.parse(localStorage.getItem("siswa")||"[]"),a=JSON.parse(localStorage.getItem("absensi")||"[]"),d=today();document.getElementById("totalSiswa").textContent=s.length;document.getElementById("hadirHariIni").textContent=a.filter(x=>x.tanggal===d&&x.status==="Hadir").length;document.getElementById("tidakHadir").textContent=a.filter(x=>x.tanggal===d&&x.status!=="Hadir").length}
function renderSiswa(){const t=document.getElementById("siswaTable"),s=JSON.parse(localStorage.getItem("siswa")||"[]");t.innerHTML=s.length?s.map((x,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(x.nis)}</td><td>${escapeHtml(x.nama)}</td><td>${escapeHtml(x.kelas)}</td><td><a class="btn" href="edit_siswa.html?id=${encodeURIComponent(x.id)}">Edit</a> <button class="danger" onclick="hapusSiswa('${x.id}')">Hapus</button></td></tr>`).join(""):`<tr><td colspan="5">Belum ada data siswa.</td></tr>`}
function hapusSiswa(id){if(!confirm("Hapus siswa ini?"))return;let s=JSON.parse(localStorage.getItem("siswa")||"[]").filter(x=>x.id!==id);let a=JSON.parse(localStorage.getItem("absensi")||"[]").filter(x=>x.siswaId!==id);localStorage.setItem("siswa",JSON.stringify(s));localStorage.setItem("absensi",JSON.stringify(a));renderSiswa()}
function loadSiswaOptions(){const el=document.getElementById("siswa");if(!el)return;const s=JSON.parse(localStorage.getItem("siswa")||"[]");el.innerHTML=s.length?s.map(x=>`<option value="${x.id}">${escapeHtml(x.nis)} - ${escapeHtml(x.nama)}</option>`).join(""):`<option value="">Belum ada siswa</option>`}
function renderAbsensi(){const t=document.getElementById("absensiTable"),s=JSON.parse(localStorage.getItem("siswa")||"[]"),a=JSON.parse(localStorage.getItem("absensi")||"[]");t.innerHTML=a.length?[...a].reverse().map((x,i)=>{const st=s.find(y=>y.id===x.siswaId);return `<tr><td>${x.tanggal}</td><td>${st?escapeHtml(st.nama):"Siswa dihapus"}</td><td>${escapeHtml(x.status)}</td><td><button class="danger" onclick="hapusAbsensi(${a.length-1-i})">Hapus</button></td></tr>`}).join(""):`<tr><td colspan="4">Belum ada absensi.</td></tr>`}
function hapusAbsensi(index){let a=JSON.parse(localStorage.getItem("absensi")||"[]");a.splice(index,1);localStorage.setItem("absensi",JSON.stringify(a));renderAbsensi()}
